GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm5hbWUiOiJNIEZhZGVsIiwiZW1haWwiOiJlbWFpbEBnbWFpbC5jb20iLCJpYXQiOjE3MjI4NTk2MTQsImV4cCI6MTcyMjg1OTYyOX0.7MEJ1EjQRtH6glssHkeQSZS_AHnjoKnr7-ByfX-_Opk

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "M Fadel",
    "email":"email@gmail.com",
    "password":"123456",
    "confPassword": "123456"
}


###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"email@gmail.com",
    "password": "123456"
}


###
GET http://localhost:5000/token


###
DELETE http://localhost:5000/logout